### ISSUE TITLE
CMake build/install CMakeLists.txt

### ISSUE THREAD

**Issue by billpriest** [mnisjk/cppWebSockets#15]
I implemented a simple build and install using cmake (I don't pretend to be a CMake guru; but it works for me).
[CMakeLists.txt](https://github.com/mnisjk/cppWebSockets/files/8207083/CMakeLists.txt)
I've only tested on Linux; but I expect it to work on other platforms that support CMake.  I didn't update the examples to use CMakeLists.txt as the Makefile(s) provided are simple enough.

**Comment by billpriest** [comment]
Ok. Previous version was a little premature.  In order for it to work correctly w/ cross compile I had to tweak it.
[CMakeLists.txt](https://github.com/mnisjk/cppWebSockets/files/8207707/CMakeLists.txt)

**Comment by mnisjk** [comment]
Hi @billpriest! If you'll submit this change as a pull request, I'd be happy to review and work towards getting this checked into the main branch

**Comment by billpriest** [comment]
Sorry, I don't have write access so it wouldn't let me push (I use gitkraken) to be able to create a pull request.  Here is a patch.

**Comment by billpriest** [comment]
[0001-Changes-to-modernize-and-fix-memory-corruption.patch.gz](https://github.com/mnisjk/cppWebSockets/files/8211407/0001-Changes-to-modernize-and-fix-memory-corruption.patch.gz)
Here is the file (you can't attach a .patch; but a .patch.gz is fine)??
